from src.utils.file_tree import merge_repo_paths, render_file_tree_markdown


def test_merge_repo_paths_deduplicates_and_sorts() -> None:
    tracked = ["src/utils/file_tree.py", "README.md", "tests/test_file_tree.py"]
    untracked = ["FILE_TREE.md", "README.md"]

    merged = merge_repo_paths(tracked=tracked, untracked=untracked)

    assert merged == [
        "FILE_TREE.md",
        "README.md",
        "src/utils/file_tree.py",
        "tests/test_file_tree.py",
    ]


def test_render_file_tree_markdown_renders_nested_structure() -> None:
    markdown = render_file_tree_markdown(
        [
            "README.md",
            "scripts/update_file_tree.py",
            "src/utils/file_tree.py",
            "tests/test_file_tree.py",
        ]
    )

    assert "# File Tree" in markdown
    assert "Generated by `scripts/update_file_tree.py`." in markdown
    assert "```text" in markdown
    assert ".\n" in markdown
    assert "├── scripts" in markdown or "└── scripts" in markdown
    assert "update_file_tree.py" in markdown
    assert "src" in markdown
    assert "file_tree.py" in markdown
