from __future__ import annotations

import subprocess
from pathlib import Path, PurePosixPath
from typing import Iterable


def merge_repo_paths(*, tracked: Iterable[str], untracked: Iterable[str]) -> list[str]:
    merged = {
        _normalize_repo_path(path)
        for path in list(tracked) + list(untracked)
        if path and _normalize_repo_path(path) != "."
    }
    return sorted(merged)


def collect_repo_paths(repo_root: Path) -> list[str]:
    tracked = _git_list_paths(repo_root=repo_root, args=["ls-files", "-z"])
    untracked = _git_list_paths(repo_root=repo_root, args=["ls-files", "--others", "--exclude-standard", "-z"])
    return merge_repo_paths(tracked=tracked, untracked=untracked)


def render_file_tree_markdown(paths: Iterable[str]) -> str:
    normalized_paths = merge_repo_paths(tracked=paths, untracked=[])
    tree = _build_tree(normalized_paths)
    lines = ["."]
    lines.extend(_render_tree_lines(tree=tree, prefix=""))

    file_count = len(normalized_paths)
    directory_count = len(_collect_directories(normalized_paths))

    header = [
        "# File Tree",
        "",
        "Generated by `scripts/update_file_tree.py`.",
        "",
        "- Scope: Git tracked files + non-ignored untracked files",
        "- Excludes: ignored/local-only content such as `.git`, `.venv`, `__pycache__`, `.DS_Store`",
        f"- Files: `{file_count}`",
        f"- Directories: `{directory_count}`",
        "",
        "```text",
        "\n".join(lines),
        "```",
        "",
    ]
    return "\n".join(header)


def _git_list_paths(*, repo_root: Path, args: list[str]) -> list[str]:
    completed = subprocess.run(
        ["git", *args],
        cwd=repo_root,
        check=True,
        capture_output=True,
        text=False,
    )
    output = completed.stdout.decode("utf-8")
    return [path for path in output.split("\x00") if path]


def _normalize_repo_path(path: str) -> str:
    return PurePosixPath(path.replace("\\", "/")).as_posix()


def _build_tree(paths: Iterable[str]) -> dict[str, dict | None]:
    tree: dict[str, dict | None] = {}
    for path in paths:
        parts = PurePosixPath(path).parts
        node = tree
        for directory in parts[:-1]:
            child = node.setdefault(directory, {})
            if child is None:
                child = {}
                node[directory] = child
            node = child
        node[parts[-1]] = node.get(parts[-1], None)
    return tree


def _render_tree_lines(*, tree: dict[str, dict | None], prefix: str) -> list[str]:
    lines: list[str] = []
    entries = sorted(tree.items(), key=lambda item: (item[1] is None, item[0].lower(), item[0]))

    for index, (name, child) in enumerate(entries):
        is_last = index == len(entries) - 1
        connector = "└── " if is_last else "├── "
        lines.append(f"{prefix}{connector}{name}")
        if isinstance(child, dict):
            child_prefix = f"{prefix}{'    ' if is_last else '│   '}"
            lines.extend(_render_tree_lines(tree=child, prefix=child_prefix))
    return lines


def _collect_directories(paths: Iterable[str]) -> set[str]:
    directories: set[str] = set()
    for path in paths:
        parts = PurePosixPath(path).parts
        for index in range(1, len(parts)):
            directories.add(PurePosixPath(*parts[:index]).as_posix())
    return directories
